// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {specializeIdentifier} from "./tokens"
export const parser = LRParser.deserialize({
  version: 14,
  states: "nQVQPOOOOQO'#Cn'#CnOOQO'#Cj'#CjQVQPOOOOQO-E6h-E6h",
  stateData: "!V~OaOS~OPPOQPORPOSPOUPOVPOWPOXPOYPOZPO[PO]PO~OUZYW[]W~",
  goto: "ncPPPPPPPPPPPPPPdPPPjQRORSRTQOR",
  nodeNames: "⚠ CharacterName ActionName StatName ElementName Program Number StringLiteral LineComment HashComment BlockComment Identifier Operator Punctuation",
  maxTerm: 18,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "*h~RvX^#ipq#iqr$^rs$kst&_uv$fvw&vxy&|yz&|z{$f{|$f|}&|}!O$f!O!P&|!P!Q'R!Q![(|![!]&|!]!^&|!^!_$^!_!`$^!`!a$^!c!})a!}#O&|#P#Q&|#R#S)a#S#T)x#T#o)a#o#p&|#p#q*b#q#r&|#y#z#i$f$g#i#BY#BZ#i$IS$I_#i$I|$JO#i$JT$JU#i$KV$KW#i&FU&FV#i~#nYa~X^#ipq#i#y#z#i$f$g#i#BY#BZ#i$IS$I_#i$I|$JO#i$JT$JU#i$KV$KW#i&FU&FV#i~$cP[~!_!`$f~$kO[~~$nWOY$kZr$krs%Ws#O$k#O#P%]#P;'S$k;'S;=`&X<%lO$k~%]OV~~%`RO;'S$k;'S;=`%i;=`O$k~%lXOY$kZr$krs%Ws#O$k#O#P%]#P;'S$k;'S;=`&X;=`<%l$k<%lO$k~&[P;=`<%l$k~&dSX~OY&_Z;'S&_;'S;=`&p<%lO&_~&sP;=`<%l&_~&yPvw$f~'RO]~~'WQ[~z{'^!P!Q(e~'aTOz'^z{'p{;'S'^;'S;=`(_<%lO'^~'sVOz'^z{'p{!P'^!P!Q(Y!Q;'S'^;'S;=`(_<%lO'^~(_OY~~(bP;=`<%l'^~(jSW~OY(eZ;'S(e;'S;=`(v<%lO(e~(yP;=`<%l(e~)RQU~!O!P)X!Q![(|~)^PU~!Q![)X~)fUZ~uv)a}!O)a!Q![)a!c!})a#R#S)a#T#o)a~){TO#S)x#S#T%W#T;'S)x;'S;=`*[<%lO)x~*_P;=`<%l)x~*eP#p#q$f",
  tokenizers: [0],
  topRules: {"Program":[0,5]},
  specialized: [{term: 11, get: (value: any, stack: any) => (specializeIdentifier(value, stack) << 1), external: specializeIdentifier}],
  tokenPrec: 45
})
