// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  CharacterName = 1,
  ActionName = 2,
  StatName = 3,
  ElementName = 4,
  Program = 5,
  Number = 6,
  StringLiteral = 7,
  LineComment = 8,
  HashComment = 9,
  BlockComment = 10,
  Identifier = 11,
  Operator = 12,
  Punctuation = 13
